### ISSUE TITLE
Lifecycle with release tags

### ISSUE THREAD

**Issue by bliemli** [linki/chaoskube#128]
We would like to automatically pull the latest stable release as soon as it is released instead of updating the tag manually. Is using the `latest` or `master` image tag safe to do so? Or would it be possible for you to tag the latest stable release accordingly with e.g. `stable` or `release`?

**Comment by linki** [comment]
You can use `latest` or `master` to get the image corresponding to the current master branch. But it might be buggy. Would that work for you?

**Comment by linki** [comment]
Otherwise we could think about adding another branch (release or stable) which points to the latest tagged version. Building on quay should work fine but setting the branch would be another manual step for each each release.

**Comment by bliemli** [comment]
Buggy won't work for us as we're using chaoskube in a production setup.

A colleague of mine just pointed me towards a project of his on GitHub where he's using travis ci and a python script to automate building and tagging container images. See https://github.com/dtschan/base-image-security, especially `travis.yml` and `update_docker_images.py`. Maybe something like this could be of help?
