### ISSUE TITLE
Add a makefile to run tests and build more easily

### ISSUE THREAD

**Issue by linki** [linki/chaoskube#146]
Currently one has to run `go test ./...` and `go build main.go` to test and build the binary.

To make it easier for people cloning/forking this repository we should add a simple Makefile to run these tasks.

**Comment by el10savio** [comment]
I had a stab at adding the two targets to the makefile :)
https://github.com/linki/chaoskube/pull/248

**Comment by linki** [comment]
@el10savio Thanks a lot! 😃
