### ISSUE TITLE
how to turn off the dry-run mode

### ISSUE THREAD

**Issue by xingyuli** [linki/chaoskube#159]
As the README documented, chaoskube default to run in the dry-run mode, that's okay, and the actual behavior align with that. After I confirmed the targets, and want to turn-off the dry-run mode, I failed. The README only mentioned users can turn off that, wondering the way to do it.

![image](https://user-images.githubusercontent.com/3337431/69110379-8c741e80-0ab5-11ea-9e92-23bb939f8415.png)

PS: I am using the version v0.14.0, via the helm chart template 3.1.2, which I thought is the latest one.

I found another issue https://github.com/linki/chaoskube/issues/103 but seems not the same thing.

**Comment by linki** [comment]
@xingyuli You can use `--no-dry-run` to turn it off.

For an example, see [here](https://github.com/linki/chaoskube/blob/v0.16.0/examples/chaoskube.yaml#L42).

**Comment by xingyuli** [comment]
Yeah, it works! Maybe you could mention this either in the README or enhance the `--help` guide.

**Comment by linki** [comment]
Good idea. Fixed in https://github.com/linki/chaoskube/commit/e9dfc0335b7f7303871b85a486b79fce5a5bdd49.
