### ISSUE TITLE
Follow Logs doesnt work on new install using Helm Chart

### ISSUE THREAD

**Issue by WtfJoke** [linki/chaoskube#161]
Hi there,

If you install chaoskube by helm using `helm install stable/chaoskube` the displayed command to follow the pods log doesn't work:

```
You can follow the logs to see what chaoskube does:

    POD=$(kubectl -n default get pods -l='app.kubernetes.io/instance=khaki-pika-chaoskube' --output=jsonpath='{.items[0].metadata.name}')
    kubectl -n default logs -f $POD 

You are running in dry-run mode. No pod is actually terminated.
```

If you execute it, following error happens:
```
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

Problem is the label 
`-l='app.kubernetes.io/instance=khaki-pika-chaoskube'` 
which should be just
`-l='app.kubernetes.io/instance=khaki-pika`

Origin in [Notes.txt](https://github.com/helm/charts/blob/master/stable/chaoskube/templates/NOTES.txt) where 
`-l='app.kubernetes.io/instance={{ template "chaoskube.fullname" . }}'` 
should be probably replaced with
`-l='app.kubernetes.io/instance={{ .Release.Name }}`

I can make a PR if you want :D

**Comment by linki** [comment]
@WtfJoke Thanks! A PR would be very welcomed.

**Comment by WtfJoke** [comment]
Fixed by https://github.com/helm/charts/pull/19321

**Comment by linki** [comment]
@WtfJoke Thank you!

**Comment by WtfJoke** [comment]
Thank you too, for reviewing and merging 👍 :)
