### ISSUE TITLE
Feature: black- and whitelisting

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [linki/chaoskube#2]
...would come in handy. I think chaosmonkey has a similar feature.

**Comment by linki** [comment]
Hi @eljefedelrodeodeljefe,

that certainly makes sense. Let's collect a list of what would be useful and not too complicated to use and implement.

I can think of
* white- and blacklisting by namespace(s)
* white- and blacklisting by label selector

blacklisting *trumps* whitelisting, I guess. So pods matching a whitelisted label selector that are in a blacklisted namespace should not be killed.

**Comment by eljefedelrodeodeljefe** [comment]
I think that concludes it to be lightweight. Sounds good to me.

**Comment by kfox1111** [comment]
Another possibility is attributes.

**Comment by linki** [comment]
@kfox1111 want do you have in mind?

something like this maybe:

* all pods with some value for an attribute (e.g. `serviceAccountName=default`)
* all pods containing at least one container with some value for an attribute (e.g. `image=nginx` )

**Comment by linki** [comment]
@eljefedelrodeodeljefe @kfox1111 Label based solution is here: https://github.com/linki/chaoskube/pull/5. Let me know what you think.

**Comment by linki** [comment]
@eljefedelrodeodeljefe Namespace-based filtering, both white- and blacklisting supported, no regexp shenanigans: https://github.com/linki/chaoskube/pull/9#issue-206983465

**Comment by linki** [comment]
Label-based and namespace-based selection is part of the [v0.4.0 release](https://github.com/linki/chaoskube/releases/tag/v0.4.0)

I'm going to close this and create a new issue for attribute based filtering: https://github.com/linki/chaoskube/issues/12

**Comment by linki** [comment]
thanks @eljefedelrodeodeljefe and @kfox1111 for the suggestions!
