### ISSUE TITLE
Using curl command

### ISSUE THREAD

**Issue by 2020testuser** [linki/chaoskube#218]
Hi,
Could you please let me know whether I can use a curl command to execute chaoskube ?
Ex is below.
I'm calling chaoskube in my chaos script and so using curl cmd would be easy.
`
curl -X POST -H 'Content-Type: application/json'
                         -d '{"token":"mytoken","url":"https://<hostname>:portno",
                          "interval":10, 
                         "namespaces":"my-namespace",
                         "minimum-age":"0s"
                         }'
                          http://<hosname>:<portno-of-chaoskube>
`

**Comment by linki** [comment]
Can you explain a little more what you are doing?

**Comment by 2020testuser** [comment]
@linki - Thanks!
I want to use the curl command to start chaoskube  (from my startup script) and pass the arguments for it from within the startup script of my application test file.

Please let me know whether using a curl command to start chaoskube to kill pods is possible. Thanks in advance.

**Comment by 2020testuser** [comment]
@linki - Could you please let me know whether the above is possible? If you need more information, please let me know.
Thanks!

**Comment by linki** [comment]
Currently chaoskube doesn't have an HTTP endpoint which you can use to trigger a termination. So from what I understand your use case is not supported.

However, if you have access to the target cluster you could just **start** chaoskube which then executes the terminations as usual. You could use `curl` to schedule the Pod in the Kubernetes cluster using HTTP.

If that would work for you we'd need to add a `--once` flag to chaoskube which would make it start, terminate a single random pod and then exit again. This would be very easy to add if needed.

**Comment by 2020testuser** [comment]
@linki - Thanks Much! Will close this issue.
