### ISSUE TITLE
kinds argument available?

### ISSUE THREAD

**Issue by 8160960572** [linki/chaoskube#257]
I have deployed helm chart 3.2.1. Image version: quay.io/linki/chaoskube:v0.14.0

bash-4.2# helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
chaoskube       default         1               2020-09-28 19:00:20.913123219 +0530 IST deployed        chaoskube-3.2.1 0.14.0

I see kinds not available in values.yaml. If I try from --set kinds='Deployments', that doesn't make any difference.
If I edit the deployment manually (referred from https://github.com/linki/chaoskube/blob/master/examples/chaoskube.yaml), then below comes in logs.

-bash-4.2# kubectl logs -f chaoskube-587dc45bbd-nj6xm
chaoskube: error: unknown long flag '--kinds', try --help

So is it supported?

Expectation: kinds parameter should work to select/exclude intended k8s object kind.

**Comment by linki** [comment]
Yes, I just released `v0.21.0` which contains the new `--kinds` flag.

Please use image `quay.io/linki/chaoskube:v0.21.0`.
