### ISSUE TITLE
Create more chaos during business hours

### ISSUE THREAD

**Issue by klautcomputing** [linki/chaoskube#35]
Chaoskube should be able to create more chaos during hours where people are around to notice, fix and learn from failures. It makes no sense for the artificial chaos to occur at night and get people paged when they are asleep.

**Comment by klautcomputing** [comment]
I started working on this.

**Comment by linki** [comment]
Agreed, what do you have in mind for tackling this?

**Comment by klautcomputing** [comment]
I would like to introduce 3 new flags: `--run-from`, `--run-to`, `--excludeWeekends` so that you can set them to `--run-from 9:00 --run-to 17:00 --excludeWeekends` and thereby disable killing anything during weekends and from 17:00 to 9:00.

I am basing my code on the `tick` and `interval` code I introduced for `--percentage`. The idea is to calculate the interval to the next "wakeUp" time and then sleep until it's a weekday and within working hours.

Obvious short comings are: holidays and cultures with a non western weekend schedule.

**Comment by AndreaGiardini** [comment]
Hey @klautcomputing any update on this?

**Comment by linki** [comment]
This feature was introduced in [v0.8.0](https://github.com/linki/chaoskube/releases/tag/v0.8.0) based on a different codebase and with different flags but essentially the same behaviour.

@klautcomputing I'll still have a look at your `--percentage` code as this is my personal biggest missing feature from `chaoskube` at the moment.

/cc @AndreaGiardini
