### ISSUE TITLE
Using the inClusterConfig.  This might not work.

### ISSUE THREAD

**Issue by klautcomputing** [linki/chaoskube#36]
Since https://github.com/linki/chaoskube/pull/28 I am seeing the error:

```W0707 15:17:20.480995       1 client_config.go:481] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
log: exiting because of error: log: cannot create log: open /tmp/chaoskube.chaoskube-production-
4075332500-53jjx.unknownuser.log.WARNING.20170707-151720.1: no such file or directory```

I see that the `config, err := rest.InClusterConfig()` was removed, this might just be the error.

**Comment by linki** [comment]
Sorry about that.

I can't reproduce it. Can you provide more context?

**Comment by klautcomputing** [comment]
Are you running in cluster or outside your cluster?

I have mine run inside the cluster and since #28 was merged it first gave me the error that it does not know about `--in-cluster` anymore and then when I removed that from my arguments it went into a crashbackuploop with the error message from above.

I have no idea about how you build configs in Go for kubernetes just looking at your code change
https://github.com/linki/chaoskube/pull/28/files#diff-7ddfb3e035b42cd70649cc33393fe32cL136 was removed completely. Which seems to have changed the `inCluster` behaviour.

I tried to roll your change out both on a read only FS and then on a RW FS and both times I got the error from above. Might also be related to me running it on a `FROM scratch` container.

**Comment by linki** [comment]
Alright, can you send me a link to your Dockerfile and tell me the Kubernetes environment you're running in? (GKE, Azure, minikube, custom setup, ...)

We're using the same approach in https://github.com/kubernetes-incubator/external-dns so I'd like to find out what's the issue.

**Comment by klautcomputing** [comment]
My Dockerfiles are here: https://github.com/linki/chaoskube/pull/33/files and I am running out of GKE.

**Comment by linki** [comment]
Now I see it, too. Will look into it.

**Comment by klautcomputing** [comment]
Thanks for looking into it.
