### ISSUE TITLE
Bug with gracePeriod conversion

### ISSUE THREAD

**Issue by pims** [linki/chaoskube#415]
When a graceperiod is configured, it looks like the conversion to int64 is incorrect.

```go
func deleteOptions(gracePeriod time.Duration) metav1.DeleteOptions {
	if gracePeriod < 0 {
		return metav1.DeleteOptions{}
	}

	return metav1.DeleteOptions{GracePeriodSeconds: (*int64)(&gracePeriod)}
}
```

The issue is with:
```go
GracePeriodSeconds: (*int64)(&gracePeriod)
```

since a duration default value is in nanoseconds, converting `gracePeriod` to int64 leads to using nanoseconds instead of seconds.

Example at: https://go.dev/play/p/Ee-vADPoDPt

PR incoming.

**Comment by pims** [comment]
```
I0301 19:31:00.435366 34724 kuberuntime_container.go:586] Killing container "docker://0613c6a155c02bcf56179e4d10c641e3ee01604c2f05341b7ac507ec3816d2b6" with 60000000000 second grace period
```
here's what we noticed in our cluster 🙃

**Comment by linki** [comment]
🤦‍♂️

**Comment by linki** [comment]
@pims Thanks for fixing this! 🤗
