### ISSUE TITLE
Filter namespaces by labels

### ISSUE THREAD

**Issue by swestcott** [linki/chaoskube#44]
Our cluster includes ephemeral, randomly named namespaces which are used to run automated integration tests as part of a Jenkine pipeline. Rather than tagging numerous pod with a labels to exclude them, we'd like to be able to exclude entire namespaces using labels.

This could be achieved with an additional option, `--namespace-labels`. Just wondering if this would be a useful addition? I'd happy to raise a PR for this.

**Comment by linki** [comment]
@swestcott I like that idea!

**Comment by linki** [comment]
This has been merged in https://github.com/linki/chaoskube/pull/134
