### ISSUE TITLE
Cannot disable dry run

### ISSUE THREAD

**Issue by arjunanan6** [linki/chaoskube#499]
Hi,

I'm trying to use chaoskube, and I've managed to install it successfully in my namespace containing my app deployment. By default, dryrun is set to true. 

When I run `chaoskube --no-dry-run`, I can see that it is set to false, however, if I were to immediately run `chaoskube` again, I see that it's been set back to true. I've also tried setting this when installing, but that does not change the behavior:

`helm upgrade --install chaoskube --set dryRun=false --set labels="app=worker" chaoskube/chaoskube`

What am I doing incorrectly?

**Comment by arjunanan6** [comment]
Managed to get this working by updating the values yaml file. Count this down to my limited helm knowledge! :)

**Comment by arjunanan6** [comment]
@linki There was no fix in specific. I think I just misunderstood how it worked and went by what I got from the output of `chaoskube --no-dry-run` as the actual configuration.

However, my pod logs showed that the configuration I used in my values.yaml file were being used.

**Comment by linki** [comment]
I think `--set dryRun=false` works in general but the variable name is different. Try to mimic the path from the latest `values.yaml`, for example like this:

```console
$ helm repo add chaoskube https://linki.github.io/chaoskube
$ helm repo update
$ helm install chaoskube chaoskube/chaoskube --set chaoskube.args.no-dry-run=true ...
```

**Comment by LittleTodd** [comment]
> Managed to get this working by updating the values yaml file. Count this down to my limited helm knowledge! :)

@arjunanan6 I also hit by the same issue. Can you guide how to update the values yaml files, thanks a lot.
