### ISSUE TITLE
add dumb-init

### ISSUE THREAD

**Issue by grosser** [linki/chaoskube#51]
lots of details in https://github.com/Yelp/dumb-init ... want a PR for that ?
(adding a apk package)

```
RUN apk add --no-cache dumb-init
ENTRYPOINT ["dumb-init", "--", "/bin/chaoskube"]
```

**Comment by linki** [comment]
@grosser I'm happy to take it. Did you see any issue with the current version?

**Comment by grosser** [comment]
Did not see any actual issues, but we are adding dumb-init to all our apps as precaution.
