### ISSUE TITLE
[power] chaoskube (v0.6.1) image is not available for power.

### ISSUE THREAD

**Issue by anwaazim** [linki/chaoskube#59]
I am running following os on power machine.

Linux icp1p1 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:55:56 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux

After deploying chaoskube in the host, I get following error:
 **standard_init_linux.go:185: exec user process caused "exec format error"**
The chaoskube runs well in x86 hosts, but not in power. Is there any workaround how to run that in power, is there any image available for power machine.

**Comment by linki** [comment]
@anwaazim No, there's no such image at the moment. If you want to make a PR I'm happy to include it at `quay.io/linki/chaoskube`. Maybe similar to how [flannel](https://quay.io/repository/coreos/flannel?tab=tags) does it: https://github.com/coreos/flannel/blob/master/Makefile#L46-L56.

**Comment by anwaazim** [comment]
@linki : My colleague created a pull request here for this : https://github.com/linki/chaoskube/pull/60

**Comment by linki** [comment]
The latest image is available as:

```
docker run quay.io/linki/chaoskube:v0.9.0-ppc64le
```

Any tag ending in `-ppc64le` will be built and pushed using `Dockerfile.ppc64le`. I'll try to keep them in sync.
