### ISSUE TITLE
Allow running with operator role

### ISSUE THREAD

**Issue by otrosien** [linki/chaoskube#75]
Hi,

I have a deployment where I'm using the operator role for my kubernetes namespace, so I have full access, but only within my own namespace. chaoskube becomes ready but fails to operate.

```
pods is forbidden: User \\\"system:serviceaccount:poirot-test:operator\\\" cannot list pods at the cluster scope: unauthorized access system:serviceaccount:xxxxxxxx:operator/[system:serviceaccounts system:serviceaccounts:xxxxxxxx system:authenticated]
```

**Comment by otrosien** [comment]
... readiness probe should probably fail if things like this happen.

**Comment by linki** [comment]
Perfect idea. I'll put this on my roadmap.

**Comment by linki** [comment]
I didn't have RBAC in mind. Given the current implementation it always needs pod-reader access on a global scope. Which means limiting chaoskube to one or more namespaces doesn't allow you to also restrict its access to only them. This would be desireable as well.

**Comment by bavarianbidi** [comment]
@otrosien please have a look at this PR: https://github.com/linki/chaoskube/pull/91

could you paste the used role and rolebinding?

**Comment by linki** [comment]
Created a dedicated issue for the readiness probe: https://github.com/linki/chaoskube/issues/132

Avoiding global permissions is tracked here: https://github.com/linki/chaoskube/issues/92
