### ISSUE TITLE
Allow configuration of grace period when deleting pods

### ISSUE THREAD

**Issue by Bo0mer** [linki/chaoskube#80]
Hello,

First of all, tanks for your awesome work!

It makes sense allow one to configure the grace period that K8s will give to the deleted pod before violently killing it (using `SIGKIL`). According to [the documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) the default value (at least for `delete` commands issued via `kubectl`) is 30 seconds, which I think is more than enough time for applications that supports graceful shutdown.

I've checked the code, and ATM the grace period parameter is not supplied when invoking the K8s API:
https://github.com/linki/chaoskube/blob/a4acf6fcd941dca5fba072e5cede90887e50aed3/chaoskube/chaoskube.go#L174

I've currently applied the following patch In order to kill processes almost immediately:

```diff
diff --git a/chaoskube/chaoskube.go b/chaoskube/chaoskube.go
index 645b6e8..be7828b 100644
--- a/chaoskube/chaoskube.go
+++ b/chaoskube/chaoskube.go
@@ -171,7 +171,9 @@ func (c *Chaoskube) DeletePod(victim v1.Pod) error {
 		return nil
 	}
 
-	return c.Client.Core().Pods(victim.Namespace).Delete(victim.Name, nil)
+	secs := int64(0)
+	deleteopts := &metav1.DeleteOptions{GracePeriodSeconds: &secs}
+	return c.Client.Core().Pods(victim.Namespace).Delete(victim.Name, deleteopts)
 }
 
 // filterByNamespaces filters a list of pods by a given namespace selector.
```

Please let me know if any more details are needed.
Cheers,
Ivan

**Comment by linki** [comment]
Hi @Bo0mer, thanks!

I agree, how about we add a `--grace-period` flag to `chaoskube` in order to configure that value. If unspecified we'd use the current behaviour.

I'm wondering: if it's unspecified in the `delete` call, does it use `30` or does it use whatever is defined in the pod's spec at `terminationGracePeriodSeconds`?

**Comment by linki** [comment]
This is implemented in https://github.com/linki/chaoskube/pull/110
