### ISSUE TITLE
ChaosKube Doesn't working in my K8s Cluster (GCP)

### ISSUE THREAD

**Issue by subinmt** [linki/chaoskube#83]
Hi,

I have deployed the yaml's in in the examples on my K8s cluster. It's successfully installed,but it doesn't kill any pod or anything like that. Is there any changes in installation. Can you help me please.

Regards
Subin

**Comment by alexvicegrab** [comment]
@subinmt, make sure you are not running it in --dry-run mode.

**Comment by subinmt** [comment]
@alexvicegrab , I have already confirmed that. No logs, no pods deleting this script in my cluster. Please help.

**Comment by alexvicegrab** [comment]
Perhaps try to install the Helm chart, hosted on kubernetes/charts? How are you installing?

**Comment by alexvicegrab** [comment]
What do the logs of the pods say?

**Comment by subinmt** [comment]
I was installed YAML's in example folder, but I couldn't find any logs. I yes installed in K8s cluster.

**Comment by subinmt** [comment]
Yes. See the results:
++++++
kubectl logs -f chaoskube-f488bd5df-ftpv9
time="2018-07-11T09:20:54Z" level=info msg="starting up" dryRun=false interval=1m0s version=v0.8.0
time="2018-07-11T09:20:54Z" level=info msg="connected to cluster" master="https://100.64.0.1:443" serverVersion=v1.9.6
time="2018-07-11T09:20:54Z" level=info msg="setting pod filter" annotations="chaos.alpha.kubernetes.io/enabled=true" labels= namespaces="!kube-system"
time="2018-07-11T09:20:54Z" level=info msg="setting quiet times" daysOfYear="[Apr 1 Dec24]" timesOfDay="[22:00-08:00 11:00-13:00]" weekdays="[Saturday Sunday]"
time="2018-07-11T09:20:54Z" level=info msg="setting timezone" location=UTC name=UTC offset=0
time="2018-07-11T09:20:54Z" level=error msg="failed to terminate victim" err="pods is forbidden: User \"system:serviceaccount:default:chaoskube\" cannot list pods at the cluster scope"
++++++

**Comment by alexvicegrab** [comment]
OK, now take a course on Kubernetes and RBAC

**Comment by subinmt** [comment]
Sorry, Can you please help. I am new to K8s.

**Comment by alexvicegrab** [comment]
You need to understand about K8S and RBAC, there's a lot of articles and documentation on this.

**Comment by subinmt** [comment]
Oh.. You won't help... Thanks for all your help.

**Comment by subinmt** [comment]
@alexvicegrab , I have added the following scripts to rbac.yaml
+++++
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaoskube
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - update
+++++

Now the RBAC error vanished from the pod logs, See the current pod log:
++++++
kubectl log -f chaoskube-56869c5949-n9fbn
log is DEPRECATED and will be removed in a future version. Use logs instead.
time="2018-07-11T11:51:32Z" level=info msg="starting up" dryRun=false interval=1m0s version=v0.8.0
time="2018-07-11T11:51:32Z" level=info msg="connected to cluster" master="https://100.64.0.1:443" serverVersion=v1.9.6
time="2018-07-11T11:51:32Z" level=info msg="setting pod filter" annotations="chaos.alpha.kubernetes.io/enabled=true" labels= namespaces="!kube-system"
time="2018-07-11T11:51:32Z" level=info msg="setting quiet times" daysOfYear="[Apr 1 Dec24]" timesOfDay="[]" weekdays="[Saturday Sunday]"
time="2018-07-11T11:51:32Z" level=info msg="setting timezone" location=UTC name=UTC offset=0
++++++

But still its not working. No pod deleting in my K8s cluster using this scripts.. My K8s Cluster builds in GCP via Kops. Is that anything related to that.?

**Comment by linki** [comment]
@alexvicegrab Thanks for helping out!

**Comment by linki** [comment]
@subinmt `chaoskube` has certain flags to ignore pods from being killed. The example file you used has some dummy values for them for educational purpose, such as `--excluded-days-of-year=Apr1,Dec24`. Try running it only with the flag `--no-dry-run`.

Also, have a closer look at [the example RBAC file](https://github.com/linki/chaoskube/blob/v0.9.0/examples/rbac.yaml#L5-L8): The permissions`chaoskube` needs are `list` and `delete` on `pods` resources.

**Comment by subinmt** [comment]
@linki , Thanks for your reply. I have already verified the same from my end. I have commented the "excluded days" and run with no-dry-run option. But not working the Chaoskube. Also, check the RBAC conf file and the chaoskube have the sufficient privileges like list and delete.

**Comment by nsidhaye** [comment]
@subinmt : How many namespaces are present in your Kube cluster? Are there any namespaces other than kubesystem? 

Try following command and see if there are any running pods other than kube-system. 

```
kubectl get po --all-namespaces 
```


Did you add annotation on your pods? or better comment out annotate option and concentrate only on namespaces.

As @linki suggest run with only `--no-dry-run`  & `--interval` . Comment out all other options.

**Comment by subinmt** [comment]
@nsidhaye I am working with K8s default namespace. I have already commented the  annotation and verified the same. but no use. Please help.

**Comment by bavarianbidi** [comment]
hi @subinmt 
have you set the `--namespaces`-flag in your deployment?

if you have no cluster-wide permissions to get/delete pods, you must create a role and rolebinding for the destination-namespace.

maybe this PR https://github.com/linki/chaoskube/pull/91 could help?

**Comment by ssro** [comment]
@subinmt modify your deployment and add:
```
...
spec:
  selector:
    matchLabels:
      app: chaoskube
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      serviceAccount: chaoskube
...
```
The important part is `serviceAccount: chaoskube`

HTH

**Comment by subinmt** [comment]
@ssro I tried with your entries, but the chaoskube still not working in my K8s cluster. Anyone please help

**Comment by linki** [comment]
@subinmt Could you make it work in your cluster?

**Comment by linki** [comment]
Closing. @subinmt let me know if you need any additional help.
