### ISSUE TITLE
Filter pods based on age

### ISSUE THREAD

**Issue by bakins** [linki/chaoskube#85]
Thanks for this project. I'd started to write my own when I found this.

I'd like to filter pods by there age. Our use case is to not delete pods that are younger than a certain time.

Any interest in adding a `min-age` flag? I'd be happy to do the work and submit a PR if so.

Thanks!

**Comment by linki** [comment]
@bakins Thanks! 😃

Yes, sounds interesting. Feel free to submit a PR.

**Comment by linki** [comment]
This was done in https://github.com/linki/chaoskube/pull/86. I want to revisit it and maybe add it to docs. Keeping this open for now.

**Comment by linki** [comment]
Docs were added in https://github.com/linki/chaoskube/commit/9bfe7276ccc81437200aa04f4c2fe63955c603c8
