### ISSUE TITLE
Add /healthz HTTP endpoint that can be used as a livenessProbe

### ISSUE THREAD

**Issue by bakins** [linki/chaoskube#93]
It'd be good to have an HTTP endpoint that could be used for Kubernetes readiness and liveness probes.  It could return 200 OK. We could create the HTTP listener just before the infinite for loop in a goroutine.

I'm happy to do a PR if you think this is a good idea.

**Comment by linki** [comment]
@bakins That's a very good idea!

**Comment by linki** [comment]
This was done in https://github.com/linki/chaoskube/pull/94

**Comment by linki** [comment]
Thanks @bakins 👍
